// Product catalog. Images reuse local /assets + a few stable Unsplash shots.

const IMG = {
  redVineyard: "/assets/coll-red.webp",
  rose: "/assets/coll-rose.webp",
  darkBottle: "/assets/hero-bottle.webp",
  reserve: "/assets/bottle-alt.webp",
  cigars: "/assets/cigars.webp",
  glasses: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=700&q=70",
  pour: "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?auto=format&fit=crop&w=700&q=70",
  whiskey: "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?auto=format&fit=crop&w=700&q=70",
  beer: "https://images.unsplash.com/photo-1535958636474-b021ee887b13?auto=format&fit=crop&w=700&q=70",
  beerFlight: "https://images.unsplash.com/photo-1612528443702-f6741f70a049?auto=format&fit=crop&w=700&q=70",
};

export const PRODUCTS = [
  {
    slug: "caymus-cabernet-2021",
    name: "Caymus Cabernet Sauvignon",
    category: "Wine",
    type: "Red Wine",
    region: "Napa Valley, CA",
    price: 89.99,
    rating: 4.8,
    reviews: 214,
    stock: "in",
    badge: "Staff Pick",
    featured: true,
    img: IMG.darkBottle,
    desc: "Rich and velvety with ripe dark fruit, cocoa, and a long, structured finish. A cellar-worthy crowd-pleaser that overdelivers at every dinner party.",
    notes: "Black cherry, vanilla, cocoa, toasted oak.",
    pairing: "Ribeye, braised short rib, aged cheddar, dark chocolate.",
    abv: "14.8%",
    specs: [["Region", "Napa Valley"], ["Vintage", "2021"], ["Varietal", "Cabernet Sauvignon"], ["Size", "750ml"]],
  },
  {
    slug: "whispering-angel-rose",
    name: "Whispering Angel Rosé",
    category: "Wine",
    type: "Rosé",
    region: "Provence, FR",
    price: 22.99,
    rating: 4.6,
    reviews: 309,
    stock: "in",
    badge: "Summer",
    featured: true,
    img: IMG.rose,
    desc: "The benchmark Provence rosé — pale, dry, and refreshing with delicate red berry and citrus. The bottle everyone reaches for when the weather turns.",
    notes: "Strawberry, grapefruit, white peach, mineral.",
    pairing: "Grilled shrimp, salads, soft cheeses, the porch at sunset.",
    abv: "13%",
    specs: [["Region", "Côtes de Provence"], ["Vintage", "2023"], ["Style", "Dry Rosé"], ["Size", "750ml"]],
  },
  {
    slug: "veuve-clicquot-brut",
    name: "Veuve Clicquot Brut",
    category: "Wine",
    type: "Champagne",
    region: "Champagne, FR",
    price: 59.99,
    rating: 4.7,
    reviews: 168,
    stock: "in",
    featured: true,
    img: IMG.glasses,
    desc: "The iconic Yellow Label — crisp, toasty, and endlessly celebratory. Always chilled and ready to pop for the moment that calls for it.",
    notes: "Brioche, green apple, citrus, fine bubbles.",
    pairing: "Oysters, fried chicken, celebrations of any size.",
    abv: "12%",
    specs: [["Region", "Champagne"], ["Style", "Brut"], ["Grapes", "Pinot Noir blend"], ["Size", "750ml"]],
  },
  {
    slug: "dom-perignon-vintage",
    name: "Dom Pérignon Vintage",
    category: "Wine",
    type: "Champagne",
    region: "Champagne, FR",
    price: 229.99,
    rating: 5.0,
    reviews: 52,
    stock: "low",
    badge: "Reserve",
    img: IMG.reserve,
    desc: "A landmark prestige cuvée — precise, mineral, and profound. For the occasions that truly deserve it.",
    notes: "Toasted almond, white flowers, citrus zest, chalk.",
    pairing: "Caviar, lobster, milestone moments.",
    abv: "12.5%",
    specs: [["Region", "Champagne"], ["Vintage", "2013"], ["Style", "Brut"], ["Size", "750ml"]],
  },
  {
    slug: "kim-crawford-sauvignon-blanc",
    name: "Kim Crawford Sauvignon Blanc",
    category: "Wine",
    type: "White Wine",
    region: "Marlborough, NZ",
    price: 16.99,
    rating: 4.5,
    reviews: 271,
    stock: "in",
    img: IMG.glasses,
    desc: "Bright, zesty, and aromatic with tropical fruit and a crisp finish. An easy weeknight white that never disappoints.",
    notes: "Passionfruit, grapefruit, lime, fresh herbs.",
    pairing: "Goat cheese, ceviche, summer salads.",
    abv: "13%",
    specs: [["Region", "Marlborough"], ["Vintage", "2023"], ["Varietal", "Sauvignon Blanc"], ["Size", "750ml"]],
  },
  {
    slug: "meiomi-pinot-noir",
    name: "Meiomi Pinot Noir",
    category: "Wine",
    type: "Red Wine",
    region: "California, US",
    price: 21.99,
    compareAt: 25.99,
    rating: 4.6,
    reviews: 188,
    stock: "in",
    badge: "Sale",
    img: IMG.pour,
    desc: "Smooth and plush with juicy berry and a touch of mocha. The Pinot that converts non-Pinot drinkers.",
    notes: "Black cherry, strawberry, mocha, vanilla.",
    pairing: "Salmon, roast chicken, mushroom risotto.",
    abv: "13.7%",
    specs: [["Region", "California"], ["Vintage", "2022"], ["Varietal", "Pinot Noir"], ["Size", "750ml"]],
  },
  {
    slug: "la-marca-prosecco",
    name: "La Marca Prosecco",
    category: "Wine",
    type: "Sparkling",
    region: "Veneto, IT",
    price: 14.99,
    rating: 4.4,
    reviews: 142,
    stock: "in",
    img: IMG.glasses,
    desc: "Light, fresh, and gently fruity — the go-to for brunch, mimosas, and easy celebrations.",
    notes: "Green apple, honeysuckle, citrus.",
    pairing: "Brunch, prosciutto, fresh fruit.",
    abv: "11%",
    specs: [["Region", "Veneto"], ["Style", "Extra Dry"], ["Varietal", "Glera"], ["Size", "750ml"]],
  },
  {
    slug: "macallan-12-double-cask",
    name: "Macallan 12 Double Cask",
    category: "Spirits",
    type: "Single Malt Scotch",
    region: "Speyside, SCT",
    price: 74.99,
    rating: 4.9,
    reviews: 187,
    stock: "in",
    badge: "Top Rated",
    featured: true,
    img: IMG.whiskey,
    desc: "Honeyed sweetness, dried fruit, and warm oak from sherry-seasoned casks. A benchmark single malt and a frequent gift.",
    notes: "Honey, dried fruit, vanilla, gentle spice.",
    pairing: "Neat, a single cube, or a fine cigar.",
    abv: "40%",
    specs: [["Region", "Speyside"], ["Age", "12 Years"], ["ABV", "40%"], ["Size", "750ml"]],
  },
  {
    slug: "buffalo-trace-bourbon",
    name: "Buffalo Trace Bourbon",
    category: "Spirits",
    type: "Bourbon",
    region: "Kentucky, US",
    price: 29.99,
    rating: 4.7,
    reviews: 263,
    stock: "low",
    badge: "Value",
    img: IMG.whiskey,
    desc: "Award-winning Kentucky straight bourbon — caramel, vanilla, and gentle spice at a fair price. Hard to keep on the shelf.",
    notes: "Caramel, vanilla, brown sugar, light oak.",
    pairing: "Old Fashioned, neat, or over a big cube.",
    abv: "45%",
    specs: [["Region", "Kentucky"], ["Style", "Straight Bourbon"], ["ABV", "45%"], ["Size", "750ml"]],
  },
  {
    slug: "casamigos-blanco-tequila",
    name: "Casamigos Blanco Tequila",
    category: "Spirits",
    type: "Tequila",
    region: "Jalisco, MX",
    price: 48.99,
    rating: 4.5,
    reviews: 142,
    stock: "in",
    img: IMG.whiskey,
    desc: "Soft agave, vanilla, and a clean, smooth finish — built for sipping or a standout margarita.",
    notes: "Agave, vanilla, citrus, light pepper.",
    pairing: "Margaritas, tacos, fresh lime.",
    abv: "40%",
    specs: [["Region", "Jalisco"], ["Style", "Blanco"], ["ABV", "40%"], ["Size", "750ml"]],
  },
  {
    slug: "hendricks-gin",
    name: "Hendrick's Gin",
    category: "Spirits",
    type: "Gin",
    region: "Scotland",
    price: 36.99,
    rating: 4.6,
    reviews: 121,
    stock: "in",
    img: IMG.whiskey,
    desc: "Distinctly smooth with cucumber and rose. The gin that made a generation rethink the G&T.",
    notes: "Cucumber, rose, juniper, citrus.",
    pairing: "G&T with cucumber, a crisp martini.",
    abv: "44%",
    specs: [["Region", "Scotland"], ["Style", "London Dry"], ["ABV", "44%"], ["Size", "750ml"]],
  },
  {
    slug: "titos-handmade-vodka",
    name: "Tito's Handmade Vodka",
    category: "Spirits",
    type: "Vodka",
    region: "Texas, US",
    price: 24.99,
    rating: 4.7,
    reviews: 340,
    stock: "in",
    badge: "Best Seller",
    img: IMG.whiskey,
    desc: "Clean, smooth, gluten-free, and impossibly versatile — the house pour for a reason.",
    notes: "Clean, slightly sweet, smooth.",
    pairing: "Anything from a Moscow Mule to a martini.",
    abv: "40%",
    specs: [["Region", "Texas"], ["Style", "Corn Vodka"], ["ABV", "40%"], ["Size", "750ml"]],
  },
  {
    slug: "eastern-shore-ipa",
    name: "Eastern Shore IPA — 6 Pack",
    category: "Beer",
    type: "Craft IPA",
    region: "Maryland, US",
    price: 14.99,
    rating: 4.4,
    reviews: 96,
    stock: "in",
    badge: "Local",
    featured: true,
    img: IMG.beerFlight,
    desc: "A hazy, citrus-forward IPA from just up the road. Hopped for a warm Cambridge evening on the porch.",
    notes: "Citrus, tropical fruit, pine, soft bitterness.",
    pairing: "Spicy wings, burgers, fish tacos.",
    abv: "6.8%",
    specs: [["Style", "Hazy IPA"], ["ABV", "6.8%"], ["Pack", "6 × 12oz"], ["Brewery", "Local MD"]],
  },
  {
    slug: "rar-brewing-lager",
    name: "RAR Brewing Lager — 6 Pack",
    category: "Beer",
    type: "Craft Lager",
    region: "Cambridge, MD",
    price: 11.99,
    rating: 4.3,
    reviews: 74,
    stock: "in",
    badge: "Local",
    img: IMG.beer,
    desc: "Brewed right here in Cambridge — crisp, clean, and impossibly easy-drinking. Hometown pride in a can.",
    notes: "Crisp, bready, clean finish.",
    pairing: "Crab feast, pizza, a hot afternoon.",
    abv: "4.8%",
    specs: [["Style", "Lager"], ["ABV", "4.8%"], ["Pack", "6 × 12oz"], ["Brewery", "RAR, Cambridge"]],
  },
  {
    slug: "guinness-draught",
    name: "Guinness Draught — 8 Pack",
    category: "Beer",
    type: "Stout",
    region: "Ireland",
    price: 13.99,
    rating: 4.6,
    reviews: 158,
    stock: "low",
    img: IMG.beer,
    desc: "The legendary dry Irish stout — roasted, creamy, and smooth with that perfect cascading pour.",
    notes: "Roasted malt, coffee, cocoa, cream.",
    pairing: "Oysters, shepherd's pie, sharp cheddar.",
    abv: "4.2%",
    specs: [["Style", "Dry Stout"], ["ABV", "4.2%"], ["Pack", "8 × 14.9oz"], ["Origin", "Ireland"]],
  },
  {
    slug: "cohiba-robusto",
    name: "Cohiba Robusto",
    category: "Cigars",
    type: "Premium Cigar",
    region: "Dominican Rep.",
    price: 24.99,
    rating: 4.9,
    reviews: 118,
    stock: "in",
    badge: "Humidor",
    featured: true,
    img: IMG.cigars,
    desc: "Medium-to-full bodied with cedar, cream, and a touch of spice. Kept flawless in our walk-in cedar humidor.",
    notes: "Cedar, cream, leather, gentle spice.",
    pairing: "Aged rum, single malt, an unhurried evening.",
    abv: "—",
    specs: [["Origin", "Dominican Rep."], ["Wrapper", "Connecticut"], ["Size", "Robusto 5×50"], ["Strength", "Medium-Full"]],
  },
  {
    slug: "arturo-fuente-hemingway",
    name: "Arturo Fuente Hemingway",
    category: "Cigars",
    type: "Premium Cigar",
    region: "Dominican Rep.",
    price: 18.99,
    rating: 4.8,
    reviews: 91,
    stock: "in",
    img: IMG.cigars,
    desc: "A perennial favorite — smooth, nutty, and beautifully constructed in a classic figurado shape.",
    notes: "Cedar, nuts, cinnamon, light pepper.",
    pairing: "Bourbon, espresso, a slow Sunday.",
    abv: "—",
    specs: [["Origin", "Dominican Rep."], ["Wrapper", "Cameroon"], ["Size", "Short Story 4×49"], ["Strength", "Medium"]],
  },
  {
    slug: "quorum-shade",
    name: "Quorum Shade — Box of 20",
    category: "Cigars",
    type: "Everyday Cigar",
    region: "Nicaragua",
    price: 79.99,
    rating: 4.4,
    reviews: 140,
    stock: "in",
    badge: "Box Deal",
    img: IMG.cigars,
    desc: "An everyday workhorse with a smooth Connecticut shade wrapper — outstanding value by the box.",
    notes: "Cedar, almond, light cream.",
    pairing: "Morning coffee, a round of golf.",
    abv: "—",
    specs: [["Origin", "Nicaragua"], ["Wrapper", "Connecticut Shade"], ["Count", "Box of 20"], ["Strength", "Mild-Medium"]],
  },
  {
    slug: "opus-one-2019",
    name: "Opus One 2019",
    category: "Wine",
    type: "Red Wine",
    region: "Napa Valley, CA",
    price: 449.99,
    rating: 4.9,
    reviews: 38,
    stock: "out",
    badge: "Allocated",
    img: IMG.redVineyard,
    desc: "The legendary Napa–Bordeaux collaboration. Powerful yet elegant, built to age for decades. Currently allocated — request to join the list.",
    notes: "Cassis, violet, graphite, espresso, fine tannin.",
    pairing: "Dry-aged steak, or simply on its own.",
    abv: "14.5%",
    specs: [["Region", "Napa Valley"], ["Vintage", "2019"], ["Blend", "Bordeaux blend"], ["Size", "750ml"]],
  },
  {
    slug: "josh-cellars-cabernet",
    name: "Josh Cellars Cabernet",
    category: "Wine",
    type: "Red Wine",
    region: "California, US",
    price: 13.99,
    rating: 4.5,
    reviews: 402,
    stock: "in",
    badge: "Best Seller",
    img: IMG.pour,
    desc: "Approachable, smooth, and food-friendly with soft tannins. The everyday red that keeps customers coming back by the case.",
    notes: "Blackberry, mocha, vanilla, soft spice.",
    pairing: "Weeknight pasta, burgers, pizza night.",
    abv: "13.5%",
    specs: [["Region", "California"], ["Vintage", "2022"], ["Varietal", "Cabernet Sauvignon"], ["Size", "750ml"]],
  },
  {
    slug: "veuve-du-vernay-brut",
    name: "Veuve du Vernay Brut",
    category: "Wine",
    type: "Sparkling",
    region: "France",
    price: 12.99,
    rating: 4.2,
    reviews: 88,
    stock: "in",
    img: IMG.glasses,
    desc: "A friendly, dry French sparkler — bright and clean, perfect for toasts that shouldn't break the bank.",
    notes: "Apple, pear, citrus, fine bead.",
    pairing: "Toasts, brunch, anytime bubbles.",
    abv: "11%",
    specs: [["Region", "France"], ["Style", "Brut"], ["Varietal", "Blend"], ["Size", "750ml"]],
  },
];

export const CATEGORIES = ["Wine", "Spirits", "Beer", "Cigars"];

export function getProduct(slug) {
  return PRODUCTS.find((p) => p.slug === slug) || null;
}

export function getRelated(product, n = 4) {
  return PRODUCTS.filter((p) => p.category === product.category && p.slug !== product.slug).slice(0, n);
}

export function getFeatured(n = 8) {
  return PRODUCTS.filter((p) => p.featured).slice(0, n);
}

export function categoryCount(cat) {
  return PRODUCTS.filter((p) => p.category === cat).length;
}
